# Generated by Django 6.0.7 on 2026-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_name_alter_employee_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
