# Generated by Django 6.0.7 on 2026-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_department_delete_employee_delete_role_delete'),
        ('training', '0006_trainingdoc_delete_trainingregister_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='training.trainingtype', verbose_name='Treinamentos'),
        ),
    ]
