# Generated by Django 6.0.7 on 2026-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_role_trainings'),
        ('training', '0006_trainingdoc_delete_trainingregister_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='trainings',
            field=models.ManyToManyField(to='training.trainingtype', verbose_name='Treinamentos'),
        ),
    ]
