# Generated by Django 6.0.7 on 2026-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
