# Generated by Django 6.0.7 on 2026-08-01 18:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissoes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cadastros', 'Cadastrar departamento, função, funcionário, treinamento e tipo de treinamento'), ('usuario', 'Cadastrar usuário'), ('editar', 'Editar'), ('excluir', 'Excluir')], max_length=32, verbose_name='Permissões'),
        ),
    ]
