# Generated by Django 6.0.7 on 2026-08-02 13:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_permissoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissoes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cadastros', 'Cadastrar departamento, função, funcionário, treinamento e tipo de treinamento'), ('usuario', 'Cadastrar usuário'), ('editar', 'Editar departamento, função, funcionário, treinamento e tipo de treinamento'), ('excluir', 'Excluir departamento, função, funcionário, treinamento e tipo de treinamento')], max_length=32, verbose_name='Permissões'),
        ),
    ]
