# Generated by Django 6.0.7 on 2026-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(blank=True, null=True, upload_to='training_docs/{employee_id.company.name}/{employee_id.name}/')),
                ('effectiveness', models.CharField(choices=[('E', 'Eficaz'), ('I', 'Não eficaz')], max_length=1)),
                ('aplication_data_training', models.DateField()),
                ('instructor', models.CharField(max_length=100)),
                ('evaluator', models.CharField(max_length=100)),
                ('avaling_data_training', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
    ]
