# Generated by Django 6.0.7 on 2026-08-01 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_name_alter_employee_company_and_more'),
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtype',
            name='description',
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código do Treinamento'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='aplication_data_training',
            field=models.DateField(verbose_name='Data de Aplicação do Treinamento'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='avaling_data_training',
            field=models.DateField(verbose_name='Data de Avaliação do Treinamento'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='effectiveness',
            field=models.CharField(choices=[('E', 'Eficaz'), ('I', 'Não eficaz')], max_length=1, verbose_name='Eficácia'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='evaluator',
            field=models.CharField(max_length=100, verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='instructor',
            field=models.CharField(max_length=100, verbose_name='Instrutor'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtype', verbose_name='Tipo de Treinamento'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Treinamento'),
        ),
    ]
