# Generated by Django 6.0.7 on 2026-08-02 13:21

import django.db.models.deletion
import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_department_delete_employee_delete_role_delete'),
        ('training', '0003_remove_trainingtype_description_trainingtype_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingregister',
            name='docs',
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='revision',
            field=models.IntegerField(default=0, verbose_name='Revisão'),
        ),
        migrations.CreateModel(
            name='TrainingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to=training.models.training_doc_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Funcionário')),
            ],
        ),
    ]
