# Generated by Django 6.0.7 on 2026-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainingdoc_created_at_trainingdoc_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdoc',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='trainingregister',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
