# Generated by Django 6.0.7 on 2026-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingdoc_delete_trainingregister_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingregister',
            name='avaling_data_training',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Avaliação do Treinamento'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='evaluator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='trainingregister',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrutor'),
        ),
    ]
